import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fill it up ⛽</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}></main>

      <footer className={styles.footer}>
        Coding Assignment made by:&nbsp;
        <a href="https://github.com/fritzschoff" target="_blank">
          Fritzschoff
        </a>
      </footer>
    </div>
  );
};

export default Home;
